string integrator                  # Integrator type used by OpenSim
float64 integrator_accuracy        # Integrator accuracy (maximal error)
float64 min_step_size              # Minimal internal time step for integrator
float64 stiffness                  # Default stiffness used for material if none is specified in SDF
float64 dissipation                # Default dissipation used for material if none is specified in SDF
float64 transitionVelocity         # Default transition velocity used for friction if none is specified in SDF
float64 staticFriction             # Default static friction coefficient used if none is specified in SDF
float64 dynamicFriction            # Default dynamic friction coefficient used if none is specified in SDF
float64 viscousFriction            # Default viscous friction coefficient used if none is specified in SDF
