string model_name                    # name of Gazebo Model
string link_name                     # name of Gazebo Link
string visual_name                   # name of Gazebo Visual
---
string parent_model_name             # parent model
bool cast_shadows                    # return true if cast shadows is set
float64 transparency                 # value of transparency
float64 laser_retro                  # value of laser retro
geometry_msgs/Pose pose              # pose of the visual
string geometry_type                 # type of geometry
string material_name                 # material script name
bool visible                         # returns true if model is visible
bool is_static                       # returns true if model is static
bool success                         # return true if get successful
string status_message                # comments if available
