# Arduino-Make env Variables
#ALTERNATE_CORE_PATH = ATTinyCore/avr
#ARDUINO_PREFERENCES_PATH = /home/gabs48/.arduino15/preferences.txt
ARDUINO_DIR = /home/gabs48/src/electronics/arduino-1.8.5

# Programmer type:
# !!! Important. You have to use 'make ispload' when using an ISP.
ISP_PROG = usbasp
ISP_PORT = /dev/ttyACM0

# https://github.com/SpenceKonde/ATTinyCore (1.5+)
ALTERNATE_CORE = ATTinyCore
BOARD_TAG = attiny1634
VARIANT = tinyX4
F_CPU = 1000000L

# Path to the Arduino Makefile
include /home/gabs48/src/electronics/Arduino-Makefile/Arduino.mk

